name: Build and package app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build fat jar
        run: ./gradlew uber
      - name: Upload fat jar to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JAR package
          path: app/build/libs